#!/bin/bash
#find src lib|entr -r -s "/home/psy/.platformio/penv/bin/platformio run -t build;/home/psy/.platformio/penv/bin/platformio run -t upload"
#echo .pio/build/initialize/firmware.elf |entr -r -s "pio run -e initialize -t upload && gnome-terminal pio device monitor"
#echo .pio/build/debug/firmware.bin |entr -r -s "esptool.py -b 921600 -c esp32 write_flash 0x00001000 .pio/build/debug/firmware.bin && gnome-terminal pio device monitor"
#echo .pio/build/debug/firmware.bin |entr -r -s "esptool.py -b 921600 -c esp32 write_flash 0x10000 .pio/build/debug/firmware.bin && xterm -e 'pio device monitor'"
while sleep 1; do
echo cmake-build-default-esp44/ledder.bin |entr -nr "./flashmon"
done




