// host-side stub sdkconfig. CONFIG_LEDSTREAM_MODE_WS2812, CONFIG_LEDSTREAM_CHANNELS and
// CONFIG_LEDSTREAM_LEDS_PER_CHANNEL come from the Makefile (-D).
#pragma once

// pins are irrelevant on the host, but leds_init() must compile
#define CONFIG_LEDSTREAM_CHANNEL0_PIN 0
#define CONFIG_LEDSTREAM_CHANNEL1_PIN 1
#define CONFIG_LEDSTREAM_CHANNEL2_PIN 2
#define CONFIG_LEDSTREAM_CHANNEL3_PIN 3
#define CONFIG_LEDSTREAM_CHANNEL4_PIN 4
#define CONFIG_LEDSTREAM_CHANNEL5_PIN 5
#define CONFIG_LEDSTREAM_CHANNEL6_PIN 6
#define CONFIG_LEDSTREAM_CHANNEL7_PIN 7

#define CONFIG_LEDSTREAM_MAX_MILLIAMPS 0
